# Generated by Django 5.2.1 on 2025-05-25 17:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ForumApp', '0002_alter_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(max_length=1020, validators=[django.core.validators.MinLengthValidator(5)]),
        ),
    ]
